include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    use_build_context_synchronously: ignore
    must_be_immutable: ignore
    non_constant_identifier_names: ignore
    library_private_types_in_public_api: ignore
    empty_catches: ignore
    constant_identifier_names: ignore
    deprecated_member_use: ignore
