name: lagerverwaltung
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  mobile_scanner: ^6.0.3
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.5
  http: ^1.2.2
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
